// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// getIdx
NumericVector getIdx(NumericVector x, NumericVector f, NumericVector rr, NumericVector max);
RcppExport SEXP _IBOSS_getIdx(SEXP xSEXP, SEXP fSEXP, SEXP rrSEXP, SEXP maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type f(fSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rr(rrSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type max(maxSEXP);
    rcpp_result_gen = Rcpp::wrap(getIdx(x, f, rr, max));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IBOSS_getIdx", (DL_FUNC) &_IBOSS_getIdx, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_IBOSS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
