// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// get_iboss
//' Get IBOSS subsample from one dimension  //'  //' @param x A data frame or data.table //' @param f para2 //' @param rr para3 //' @param max para4 NumericVector get_iboss(NumericVector x, Rcpp::NumericVector f, Rcpp::NumericVector rr, Rcpp::NumericVector max);
RcppExport SEXP _IBOSS_get_iboss(SEXP xSEXP, SEXP fSEXP, SEXP rrSEXP, SEXP maxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type f(fSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rr(rrSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type max(maxSEXP);
    rcpp_result_gen = Rcpp::wrap(get_iboss(x, f, rr, max));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_IBOSS_get_iboss", (DL_FUNC) &_IBOSS_get_iboss, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_IBOSS(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
