# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get IBOSS subsample from one dimension 
#' 
#' @param x A data frame or data.table
#' @param f para2
#' @param rr para3
#' @param max para4
NULL

get_iboss <- function(x, f, rr, max) {
    .Call(`_IBOSS_get_iboss`, x, f, rr, max)
}

