# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Get IBOSS sample from one dimension 
#' 
#' @param x current remainder of one column data frame or vector
#' @param f full one column dataframe or vector
#' @param rr integer, number of selected samples, rr = k / d / 2
#' @param max integer, total subsample size, k
#' @return vector of selected indices in full dataframe.
getIdx <- function(x, f, rr, max) {
    .Call('_IBOSS_getIdx', PACKAGE = 'IBOSS', x, f, rr, max)
}

